spring.datasource.url: jdbc:mysql://localhost:3306/doctors_details?useSSL=false
spring.datasource.username: root
spring.datasource.password: root

#JPA Settings
spring:
  jpa:
    hibernate:
      ddl-auto: create